version: '3.8'

services:
  service:
    build: ./
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5433:5432